language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  project: ./build/
  domain: https://exclusive-mine.surge.sh
  skip_cleanup: true
