language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: surge
  project: ./build/
  domain: https://exclusive-mine.surge.sh
